# Generated by Django 4.2.4 on 2023-08-04 04:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Equipment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("brand", models.CharField(max_length=200)),
                ("model", models.CharField(max_length=200)),
                ("manufacture_date", models.DateField()),
                ("last_maintenance_date", models.DateField()),
                ("location", models.CharField(max_length=200)),
                ("status", models.CharField(max_length=200)),
            ],
            options={
                "verbose_name": "Equipment",
                "verbose_name_plural": "Equipment",
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("quantity_in_stock", models.IntegerField()),
                ("category", models.CharField(max_length=200)),
            ],
            options={
                "verbose_name": "Product",
                "verbose_name_plural": "Products",
            },
        ),
        migrations.CreateModel(
            name="Piece",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("manufacture_date", models.DateField()),
                ("last_maintenance_date", models.DateField()),
                ("status", models.CharField(max_length=200)),
                (
                    "equipment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="assistance.equipment",
                    ),
                ),
            ],
            options={
                "verbose_name": "Piece",
                "verbose_name_plural": "Pieces",
            },
        ),
    ]
