# Generated by Django 4.2.3 on 2023-07-28 12:07

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("assistance", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="equipment",
            options={"verbose_name": "Equipment", "verbose_name_plural": "Equipment"},
        ),
        migrations.AlterModelOptions(
            name="piece",
            options={"verbose_name": "Piece", "verbose_name_plural": "Pieces"},
        ),
        migrations.AlterModelOptions(
            name="product",
            options={"verbose_name": "Product", "verbose_name_plural": "Products"},
        ),
    ]
