# Generated by Django 4.2.4 on 2023-08-17 17:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("assistance", "0002_service"),
    ]

    operations = [
        migrations.CreateModel(
            name="Assistance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("type", models.CharField(max_length=200)),
            ],
            options={
                "verbose_name": "Assistance",
                "verbose_name_plural": "Assistances",
            },
        ),
        migrations.AlterModelOptions(
            name="equipment",
            options={"verbose_name": "Equipment", "verbose_name_plural": "Equipments"},
        ),
        migrations.CreateModel(
            name="CheckOut",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.CharField(max_length=200)),
                (
                    "assistances",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="checkouts",
                        to="assistance.assistance",
                    ),
                ),
                (
                    "equipments",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="checkouts",
                        to="assistance.equipment",
                    ),
                ),
                (
                    "items",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="checkouts",
                        to="assistance.piece",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="checkouts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "CheckOut",
                "verbose_name_plural": "CheckOuts",
            },
        ),
        migrations.AddField(
            model_name="assistance",
            name="equipments",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="assistances",
                to="assistance.equipment",
            ),
        ),
    ]
