# Generated by Django 4.2.4 on 2023-08-17 17:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("assistance", "0003_assistance_alter_equipment_options_checkout_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="checkout",
            name="assistances",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="checkouts",
                to="assistance.assistance",
            ),
        ),
        migrations.AlterField(
            model_name="checkout",
            name="equipments",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="checkouts",
                to="assistance.equipment",
            ),
        ),
        migrations.AlterField(
            model_name="checkout",
            name="items",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="checkouts",
                to="assistance.piece",
            ),
        ),
    ]
