# Generated by Django 4.2.4 on 2023-08-17 17:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "assistance",
            "0004_alter_checkout_assistances_alter_checkout_equipments_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="assistance",
            name="type",
            field=models.CharField(
                choices=[("maintenance", "Manutenção"), ("repair", "Conserto")],
                max_length=200,
            ),
        ),
    ]
