# Generated by Django 4.2.4 on 2023-08-17 19:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("assistance", "0005_alter_assistance_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="checkout",
            name="status",
            field=models.CharField(
                choices=[("Pendente", "Pendente"), ("Finalizado", "Finalizado")],
                default="Pendente",
                max_length=20,
            ),
        ),
    ]
