# Generated by Django 4.2.4 on 2023-08-17 19:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("assistance", "0006_checkout_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="equipment",
            name="description",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="equipment",
            name="model",
            field=models.CharField(
                choices=[("athletic", "Athletic")], default="athletic", max_length=200
            ),
        ),
        migrations.AlterField(
            model_name="equipment",
            name="status",
            field=models.CharField(
                choices=[("new", "Novo"), ("semi-new", "Semi-novo")], max_length=20
            ),
        ),
    ]
