# Generated by Django 4.2.4 on 2023-08-18 11:58

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("assistance", "0008_alter_equipment_brand_alter_equipment_model"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Service",
        ),
    ]
