# Generated by Django 4.2.4 on 2023-09-05 18:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("assistance", "0011_piece_image_product_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="equipment",
            name="image",
        ),
        migrations.AddField(
            model_name="equipment",
            name="imagem",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
    ]
