# Generated by Django 4.2.4 on 2023-09-14 19:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("assistance", "0013_rename_imagem_equipment_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="equipment",
            name="brand",
            field=models.CharField(
                choices=[("athletic", "Athletic"), ("supergold", "SuperGold")],
                default="athletic",
                max_length=200,
            ),
        ),
    ]
