# Generated by Django 4.2.4 on 2023-09-18 10:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("uploader", "0001_initial"),
        ("assistance", "0014_alter_equipment_brand"),
    ]

    operations = [
        migrations.AlterField(
            model_name="equipment",
            name="image",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="uploader.image",
            ),
        ),
    ]
