# Generated by Django 4.2.4 on 2023-09-19 01:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("assistance", "0015_alter_equipment_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="equipment",
            name="last_maintenance_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="equipment",
            name="manufacture_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
