# Generated by Django 4.2.4 on 2023-09-19 01:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("assistance", "0017_alter_equipment_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="equipment",
            name="brand",
            field=models.CharField(
                blank=True,
                choices=[("athletic", "Athletic"), ("supergold", "SuperGold")],
                default="athletic",
                max_length=200,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="equipment",
            name="location",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="equipment",
            name="model",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
