# Generated by Django 4.2.4 on 2023-09-20 07:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("assistance", "0018_alter_equipment_brand_alter_equipment_location_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="equipment",
            name="location",
            field=models.CharField(default="brazil", max_length=200),
            preserve_default=False,
        ),
    ]
