# Generated by Django 4.2.4 on 2023-09-21 01:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("assistance", "0020_remove_equipment_location"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="equipment",
            name="last_maintenance_date",
        ),
        migrations.RemoveField(
            model_name="equipment",
            name="manufacture_date",
        ),
    ]
