# Generated by Django 4.2.4 on 2023-09-21 02:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("uploader", "0001_initial"),
        ("assistance", "0022_delete_checkout"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Product",
            new_name="Item",
        ),
        migrations.AlterModelOptions(
            name="item",
            options={"verbose_name": "Item", "verbose_name_plural": "Items"},
        ),
        migrations.DeleteModel(
            name="Piece",
        ),
    ]
