# Generated by Django 4.2.5 on 2023-10-13 03:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("assistance", "0024_cart_cartitem"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cart",
            name="created_at",
        ),
        migrations.AlterField(
            model_name="cartitem",
            name="equipment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="assistance.equipment",
            ),
        ),
        migrations.AlterField(
            model_name="cartitem",
            name="item",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="assistance.item",
            ),
        ),
    ]
