# Generated by Django 4.2.5 on 2023-10-13 18:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("assistance", "0026_cart_created_at_alter_cartitem_equipment_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="equipment",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[("new", "Novo"), ("semi-new", "Semi-novo")],
                default=None,
                max_length=20,
                null=True,
            ),
        ),
    ]
