# Generated by Django 4.2.5 on 2023-11-06 04:49

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("assistance", "0027_alter_equipment_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="equipment",
            name="brand",
        ),
        migrations.RemoveField(
            model_name="equipment",
            name="status",
        ),
    ]
