# Generated by Django 4.2.5 on 2023-11-06 12:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("uploader", "0001_initial"),
        ("assistance", "0029_rename_image_equipment_cover"),
    ]

    operations = [
        migrations.AlterField(
            model_name="equipment",
            name="cover",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="equipment_cover",
                to="uploader.image",
            ),
        ),
    ]
