# Generated by Django 4.2.5 on 2023-11-06 12:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("uploader", "0001_initial"),
        ("assistance", "0030_alter_equipment_cover"),
    ]

    operations = [
        migrations.AlterField(
            model_name="equipment",
            name="cover",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="uploader.image",
            ),
        ),
    ]
