# Generated by Django 4.2.5 on 2023-11-11 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistance', '0031_alter_equipment_cover'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='is_on_promotion',
            field=models.BooleanField(default=False, verbose_name='Em Promoção'),
        ),
    ]
