# Generated by Django 4.2.4 on 2023-08-17 18:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0002_alter_user_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="bairro",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="Neighborhood"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="cep",
            field=models.CharField(
                blank=True, max_length=8, null=True, verbose_name="CEP"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="complemento",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="Complement"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="localidade",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="City"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="logradouro",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="Street"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="uf",
            field=models.CharField(
                blank=True, max_length=2, null=True, verbose_name="State"
            ),
        ),
    ]
