# Generated by Django 4.2.4 on 2023-09-19 15:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("uploader", "0001_initial"),
        ("user", "0003_user_bairro_user_cep_user_complemento_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="image",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="uploader.image",
            ),
        ),
    ]
