# Generated by Django 4.2.5 on 2023-11-11 15:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0004_user_image"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="image",
            new_name="cover",
        ),
    ]
